##### Config File for Kendall Correlation Map for Descriptors #####


path:
  adsorption_energy_file: "data/EadsCO.csv"
  element_descriptor_file: "data/element-descriptors.csv"
  electronic_descriptor_file: "data/electronic-descriptors.csv"


plot:
  descriptors: ["Eads", "d_band_centre_up", "lattice_para_γ", "vacuum_level", "Electronegativity-Allen"]  # plot most correlated descriptors
  descriptor_symbol_dict: {
    "Eads":'${E_\mathregular{ads}}$',
    "d_band_centre_up":'$\mathregular{\delta\epsilon_{d\uparrow}}$',  # ref: 10.1073/pnas.1006652108
    "lattice_para_γ":'$\gamma$',
    "vacuum_level":'${E_\mathregular{vac}}$',  # ref: 10.1039/C5MH00160A
    "Electronegativity-Allen":'$\mathregular{\chi_{Allen}}$',
    }
