##### Config File for Shifting Experiment #####

path:
  working_dir: "data/g-C3N4_CO_is"
  cnn_model_path: "../1-model-and-training/2-best-model/model"
  adsorbate_dos_array_path: "../0-dataset/feature_DOS/adsorbate-DOS/3-CO/dos_up_adsorbate.npy"
  prediction_saving_path: "result_predictions"

shifting:
  dos_array_name: "dos_up.npy"
  dos_calculation_resolution: 0.005
  max_adsorbate_channels: 5
  remove_ghost_state: True
  shifting_range: [-1, 1]
  shifting_step: 0.005
  shifting_orbitals: [4,5,6,7,8]  # starts from ZERO
