##### Config File for Limiting Potential Periodic Table #####

path:
  limiting_potential_file: "../5-volcano-plot/src/test/debug_results/diff_limiting_potential.csv"
  data_cols: {"name":0, "limiting_potential":1}


  