##### Config File for Kendall Correlation Map for Descriptors #####


path:
  adsorption_energy_file: "data/EadsCO.csv"
  element_descriptor_file: "data/element-descriptors.csv"
  electronic_descriptor_file: "data/electronic-descriptors.csv"


plot:
  descriptor_symbol_dict: {
      "Eads":'$\mathregular{E_{ads}}$',

      "atomic_radius":"R",
      "valence_ele_num":"V",  # TODO: no ref
      "d_ele_num":'$\mathit{e_d}$',  # TODO: no ref  #DEBUG: confirm style (Italian or not)
      "relative_atomic_mass":'$\mathregular{A_{r}}$',  # ref: CRC book 95th ed page 2-29
      "electron_affinity":'$\mathregular{E_{ea}}$',  # ref: CRC book 95th ed page 8-5
      "ionization_energy":'$\mathregular{E_{i}}$',  # ref: CRC book 95th ed page 2-4
      "work_function_DFT":'$\Phi_{\mathrm{DFT}}$',

      "work_function":'$\Phi$',  # ref: CRC book 95th ed page 2-7
      "Electronegativity-Allen":'$\mathregular{\chi_{Allen}}$',
      "Electronegativity-Pauling":'$\mathregular{\chi_{P}}$',
      "Electronegativity-Revised_Pauling":'$\mathregular{\chi_{RevP}}$',

      "d_band_centre_up":'$\mathregular{\delta\epsilon_{d\uparrow}}$',  # ref: 10.1073/pnas.1006652108
      "d_band_centre_down":'$\mathregular{\delta\epsilon_{d\downarrow}}$',  # ref: 10.1073/pnas.1006652108
      "d_band_width_up":  '$\mathregular{W_{d\uparrow}}$',  # ref: 10.1007/s11244-013-0159-2
      "d_band_width_down":  '$\mathregular{W_{d\downarrow}}$',  # ref: 10.1007/s11244-013-0159-2


      "lattice_para_a":'$\alpha$',
      "lattice_para_b":'$\beta$',
      "lattice_para_Î³":'$\gamma$',
      "vacuum_level":'$\mathregular{E_{vac}}$',  # ref: 10.1039/C5MH00160A 

      "bandgap_up":'$\mathregular{E_{g\uparrow}}$',  # ref: https://en.wikipedia.org/wiki/Band_gap
      "bandgap_down":'$\mathregular{E_{g\downarrow}}$',
      "bandgap_total":'$\mathregular{E_{g}}$',
      "Bader_charge_metal":'$\mathit{e_{Bader}}$',  # ref: CRC book 95th ed page 1-1 for "elementary charge"  # DEBUG: confirm style (Italian or not)

      "Period_num":"P",
      "Group_num":"G",
      }  
