##### Config File for d-Band Calculations #####

path:
  dos_dir: "../0-dataset/feature_DOS"
  label_dir: "../0-dataset/label_adsorption_energy"
  fermi_level_dir: "../0-dataset/z-supporting-info/fermi_level"


species:
  adsorbates: ["3-CO_is", ]
  substrates: ["g-C3N4", "nitrogen-graphene", "vacant-graphene", "C2N", "BN", "BP"]


calculation:
  energy_range: [-14, 6]
