##### Config File for Volcano Plot #####

path:
  perturbation_analysis_dir: "../1-perturbation-analysis"
  dos_filename: "dos_up_INDEX.npy"
  adsorbate_dosfile: "../../0-dataset/feature_DOS/adsorbate-DOS/3-CO/dos_up_adsorbate.npy"
  label_dir: "data"

species:
  adsorbate_maxAtoms: 5
