##### Config File for Occlusion Experiment #####

path:
  cnn_model_path: "../1-model-and-training/2-best-model/model"
  adsorbate_dos_array_path: "../0-dataset/feature_DOS/adsorbate-DOS/3-CO/dos_up_adsorbate.npy"
  fermi_level_source: "../0-dataset/z-supporting-info/fermi_level"

occlusion:
  dos_array_name: "dos_up.npy"
  max_adsorbate_channels: 5
  remove_ghost_state: True
  dos_calculation_resolution: 0.005
  occlusion_width: 1
  occlusion_step: 1
  save_predictions: True

plotting:
  dos_energy_range: [-14, 6]
  plot_energy_range: [-10, 5]
  heatmap_orbitals: ["d", ]
  line_orbitals: ["s", "p", "d"]
  orbital_names: ["s", "$p_y$", "$p_z$", "$p_x$", "$d_{xy}$", "$d_{yz}$", "$d_{z^2}$", "$d_{xz}$", "$d_{x^2-y^2}$"]
