##### Config File for Volcano Plot #####

path:
  adsorption_energy_path: "../0-dataset/label_adsorption_energy"
  reaction_pathway_file: "data/reaction_pathway.json"
  thermal_correction_file: "data/corrections_thermal.csv"
  adsorbate_energy_file: "data/energy_adsorbate.csv"


species:
  substrates: ["g-C3N4_is", "nitrogen-graphene_is", "vacant-graphene_is", "C2N_is", "BN_is", "BP_is"]
  adsorbates: ["2-COOH", "3-CO", "4-OCH", "5-OCH2", "6-OCH3", "7-O", "8-OH", "11-H"]
  

reaction:
  descriptor_x: "3-CO"
  descriptor_y: "8-OH"
  group_x: ["1-CO2", "2-COOH", "3-CO"]
  group_y: ["4-OCH", "5-OCH2", "6-OCH3", "7-O", "8-OH", "11-HER"]


corrections:
  external_potential: 0.17


plot:
  markers: ["o", "^", "s", "d", "P", "*"]
  label_selection: ["g-C3N4_is", "nitrogen-graphene_is", "vacant-graphene_is"]
  x_range: [-5, 0.5]
  y_range: [-6.5, 0]
