##### Config File for Volcano Plot #####

path:
  adsorption_energy_path: "../0-dataset/label_adsorption_energy"
  reaction_pathway_file: "data/reaction_pathway.csv"
  free_energy_correction_file: "data/correction_free_energy.csv" 


species:
  substrates: ["g-C3N4", "nitrogen-graphene", "vacant-graphene", "C2N", "BN", "BP"]
  adsorbates: ["1-CO2", "2-COOH", "3-CO", "4-OCH", "5-OCH2", "6-OCH3", "7-O", "8-OH", "11-HER"]
  

reaction:
  external_potential: 0.17 
  descriptor_x: "3-CO"
  descriptor_y: "8-OH"
  group_x: ["1-CO2", "2-COOH", "3-CO"]  # "HER"?
  group_y: ["4-OCH", "5-OCH2", "6-OCH3", "7-O", "8-OH"]

  