#!/bin/bash 
#PBS -N testgpu
#PBS -l ncpus=12
#PBS -l ngpus=1
#PBS -l mem=192GB
#PBS -l jobfs=1GB
#PBS -l walltime=0:30:00
#PBS -q gpuvolta
#PBS -P v88
#PBS -l storage=gdata/iu57+gdata/v88+gdata/dk92
#PBS -v PYTHONPATH=/g/data/v88/EXTRA_PYTHON_LIB/lib/python3.9/site-packages

cd $PBS_O_WORKDIR

# Ref: https://opus.nci.org.au/display/DAE/Tensorflow+using+ImageNet
cur_host=`hostname`
node_gpu=$((PBS_NGPUS / PBS_NNODES))
for node in `cat $PBS_NODEFILE | uniq`
do
    if [[ $node == $cur_host ]]
    then
       host_flag="${node}:${node_gpu}"
    else
       host_flag="${host_flag},${node}:${node_gpu}"
    fi
done

module use /g/data/dk92/apps/Modules/modulefiles
module load NCI-ai-ml/22.08

# Print nodeID for gpustat connection
echo "Node ID: `uniq $PBS_NODEFILE`" > tunerlog


# Run Horovod
horovod.ini.sh
horovodrun -np ${PBS_NGPUS} --gloo -H ${host_flag} -p 1212 \
	python3 keras-tuner.py >> tunerlog 2>&1
