#!/bin/bash 
#PBS -N keras-tuner
#PBS -l ncpus=24
#PBS -l ngpus=2
#PBS -l mem=96GB
#PBS -l jobfs=1GB
#PBS -l walltime=1:59:00
#PBS -q gpuvolta
#PBS -P v88
#PBS -l storage=gdata/iu57+gdata/v88+gdata/dk92
#PBS -v PYTHONPATH=/g/data/iu57/EXTRA_PYTHON_LIB

cd $PBS_O_WORKDIR

# Activate conda environment
eval "$(conda shell.bash hook)"  # https://hpc-unibe-ch.github.io/software/Anaconda.html
conda activate tensorflow

# Run script
python3 training.py > cnnlog 2>&1

