##### Config File for Kendall Correlation Map for Descriptors #####


path:
  adsorption_energy_file: "data/EadsCO.csv"
  element_descriptor_file: "data/element-descriptors.csv"
  electronic_descriptor_file: "data/electronic-descriptors.csv"
