##### Config File for Volcano Plot #####

path:
  adsorption_energy_path: "../../dataset/label_adsorption_energy"
  reaction_pathway_file: "../../5-volcano-plot/data/reaction_pathway.json"
  thermal_correction_file: "../../5-volcano-plot/data/corrections_thermal.csv"
  adsorbate_energy_file: "../../5-volcano-plot/data/energy_adsorbate.csv"


species:
  substrates: ["g-C3N4_is", "nitrogen-graphene_is", "vacant-graphene_is", "C2N_is", "BN_is", "BP_is"]
  adsorbates: ["1-CO2", "2-COOH", "3-CO", "4-CHO", "5-CH2O", "6-OCH3", "7-O", "8-OH", "11-H"]


reaction:
  descriptor_x: "3-CO"
  descriptor_y: "8-OH"
  group_x: ["1-CO2", "2-COOH", "3-CO"]
  group_y: ["4-CHO", "5-CH2O", "6-OCH3", "7-O", "8-OH", "11-HER"]

