##### Config File for Shifting Experiment #####

# DEBUG: generate a template if not found

path:
  working_dir: "testdata_g-C3N4_CO_is"  # DEBUG
  cnn_model_path: "../1-model-and-training/2-best-model/model"
  adsorbate_dos_array_path: "../0-dataset/feature_DOS/adsorbate-DOS/3-CO/dos_up_adsorbate.npy"

shifting:
  dos_array_name: "dos_up.npy"
  max_adsorbate_channels: 5
  remove_ghost_state: True
  shifting_range: [-1, 1]
  shifting_step_length: 0.05
  shifting_orbitals: [0]  # starts from ZERO
  result_array_name: "shifting_diff.npy"
