##### Config File for Occlusion Width Test #####

path:
  occlusion_script: "./lib/generate_occlusion.py"
  example_dos: "../../0-dataset/feature_DOS/g-C3N4/3-CO_is/4-Ge/dos_up_57.npy"


test:
  widths: [1, 3, 5, 11, 21, 31, 41, 51]
  